version: "3"

services:

  db-author:
    image: postgres:11
    environment:
      - POSTGRES_USER=magnolia
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - db-author-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  db-public:
    image: postgres:11
    environment:
      - POSTGRES_USER=magnolia
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - db-public-data:/var/lib/postgresql/data
    ports:
      - 15432:15432

  author:
    image: magnolia/magnolia-ce-pgsql:6.0-9.0.13-jre11-slim
    ports:
      - 3000:8080
    environment:
      - IS_AUTHOR=true
      - DB_ADDRESS=db-author
      - DB_PORT=5432
      - DB_SCHEMA=magnolia
      - DB_USERNAME=magnolia
      - DB_PASSWORD=mysecretpassword
    volumes:
      - ./magnolia-demo-webapp/target/magnolia-demo-webapp-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    labels:
      - "traefik.http.routers.author.rule=Host(`${MAGNOLIA_AUTHOR_HOST:-author.lvh.me}`)"
      - "traefik.http.services.author.loadBalancer.server.port=8080"
      - "traefik.http.routers.author.entryPoints=web"

  public:
    image: magnolia/magnolia-ce-pgsql:6.0-9.0.13-jre11-slim
    environment:
      - IS_AUTHOR=false
      - DB_ADDRESS=db-public
      - DB_PORT=5432
      - DB_SCHEMA=magnolia
      - DB_USERNAME=magnolia
      - DB_PASSWORD=mysecretpassword
    volumes:
      - ./magnolia-demo-webapp/target/magnolia-demo-webapp-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
    labels:
      - "traefik.http.routers.public.rule=Host(`${MAGNOLIA_PUBLIC_HOST:-public.lvh.me}`)"
      - "traefik.http.services.public.loadBalancer.server.port=8080"
      - "traefik.http.routers.public.entryPoints=web"

  traefik:
    image: "traefik:v2.1.3"
    ports:
      - ${TRAEFIK_HOST_PORT:-80}:80
    volumes:
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.lvh.me`)"
      - "traefik.http.routers.api.service=api@internal"


volumes:
  db-author-data:
  db-public-data: